# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aileen's ACA Blog
email: aileenhorgan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  <p>Bloggin while learnin</p>
  <p>Tryin to code</p>
  /p>Will keep you posted</p>
baseurl: "/aca-blog" # the subpath of your site, e.g. /blog
url: "http://aileener.github.io" # the base hostname & protocol for your site
twitter_username: aileenhorgan
github_username:  aileener

# Build settings
markdown: kramdown
